# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class Hand(BaseModel):
    tiles: typing.List[str]
    melds: typing.Optional[typing.List["MeldInfo"]] = None
    win_tile: typing.Optional[str] = None
    dora_indicators: typing.Optional[typing.List[str]] = None
    is_riichi: typing.Optional[bool] = None
    is_tsumo: typing.Optional[bool] = None
    is_ippatsu: typing.Optional[bool] = None
    is_rinshan: typing.Optional[bool] = None
    is_chankan: typing.Optional[bool] = None
    is_haitei: typing.Optional[bool] = None
    is_houtei: typing.Optional[bool] = None
    is_daburu_riichi: typing.Optional[bool] = None
    is_nagashi_mangan: typing.Optional[bool] = None
    is_tenhou: typing.Optional[bool] = None
    is_chiihou: typing.Optional[bool] = None
    is_renhou: typing.Optional[bool] = None
    is_open_riichi: typing.Optional[bool] = None
    player_wind: typing.Optional[str] = None
    round_wind: typing.Optional[str] = None
    kyoutaku_number: typing.Optional[int] = None
    tsumi_number: typing.Optional[int] = None

class MeldInfo(BaseModel):
    tiles: typing.List[str]
    is_open: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (2)
# #########################################################################


TileType: typing_extensions.TypeAlias = typing.Optional[str]


WindType: typing_extensions.TypeAlias = typing.Optional[str]
