# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (2)
# #########################################################################

class Hand(BaseModel):
    tiles: typing.List[str]
    melds: typing.Optional[typing.List["MeldInfo"]] = None
    win_tile: str
    dora_indicators: typing.Optional[typing.List[str]] = None
    is_riichi: bool
    is_tsumo: bool
    is_ippatsu: bool
    is_rinshan: bool
    is_chankan: bool
    is_haitei: bool
    is_houtei: bool
    is_daburu_riichi: bool
    is_nagashi_mangan: bool
    is_tenhou: bool
    is_chiihou: bool
    is_renhou: bool
    is_open_riichi: bool
    player_wind: typing.Optional[str] = None
    round_wind: typing.Optional[str] = None
    kyoutaku_number: int
    tsumi_number: int

class MeldInfo(BaseModel):
    tiles: typing.List[str]
    is_open: bool

# #########################################################################
# Generated type aliases (2)
# #########################################################################


TileType: typing_extensions.TypeAlias = str


WindType: typing_extensions.TypeAlias = str
